- work
  - 改测速失败的 bug
- python tornado 异步
  - 超时后 `futrue` 没有返回值，就会进入到 `gen.TimeoutError`
    ```python
    try:
        result = yield gen.with_timeout(datetime.timedelta(seconds=rpc_timeout), future)
    except gen.TimeoutError as e:
        pass
    ```
  - 异步程序中 `sleep` 的用法：`yield gen.sleep(1)`，如果用普通的，将让整个进程睡
  - `Future()` 在 `.set_result` 之后会消失，新建和消失需要一一对应
  - 如果一个 `Future()` 老是在被处理，另外的 `Future()` 进不来，这就是 `wan.speed_test` 接口在占用的时候，其它请求都会超时的原因
- python
  - 'ignore' 忽略非法字符，如下代码只会编码`啊`：`u'郈啊'.encode('GB2312', 'ignore')`
  - 在程序中打断点是会阻塞掉整个程序的，即使这个部分是异步出来的部分